[phases.setup]
nixPkgs = { python = "311", pip = "latest" }

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "cd backend && pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "bash start.sh"

